apiVersion: v2
name: yeti
version: 2.2.2
description: A Helm chart for Yeti Kubernetes deployments.
keywords:
- yeti
- dfir
- threatintel
- threat-hunting
- security
home: "https://yeti-platform.io/"
maintainers:
  - name: Open Source DFIR
    email: osdfir-maintainers@googlegroups.com
    url: https://github.com/google/osdfir-infrastructure
sources:
- https://github.com/yeti-platform/yeti
- https://github.com/google/osdfir-infrastructure
appVersion: "latest2"
annotations:
  category: Security
  licenses: Apache-2.0
