apiVersion: v2
name: openrelik
version: 2.2.7
description: A Helm chart for Openrelik Kubernetes deployments.
keywords:
- openrelik
- dfir
- analysis
- forensics
home: "https://openrelik.org/"
maintainers:
  - name: Open Source DFIR
    email: osdfir-maintainers@googlegroups.com
    url: https://github.com/google/osdfir-infrastructure
sources:
- https://github.com/openrelik
- https://github.com/google/osdfir-infrastructure
icon: https://openrelik.org/favicon.ico
appVersion: "latest"
annotations:
  category: Security
  licenses: Apache-2.0
