apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-yeti-beats
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: beats
    {{- include "yeti.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: beats
      {{- include "yeti.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: beats
        {{- include "yeti.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: false
      hostIPC: false
      automountServiceAccountToken: false
      initContainers:
        {{- include "yeti.initContainer" . | nindent 8 }}
      containers:
        - name: beats
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          command: ["sh", "-c", "/docker-entrypoint.sh tasks-beat"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            seccompProfile:
              type: RuntimeDefault
          env:
          {{- include "yeti.envs" . | nindent 12 }}
          resources:
            {{- toYaml .Values.beats.resources | nindent 12 }}
      {{- with .Values.beats.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}