apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-yeti-bloomcheck
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: bloomcheck
    {{- include "yeti.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: bloomcheck
      {{- include "yeti.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: bloomcheck
        {{- include "yeti.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: false
      hostIPC: false
      automountServiceAccountToken: false
      containers:
        - name: bloomcheck
          image: "{{ .Values.bloomcheck.image.repository }}:{{ .Values.bloomcheck.image.tag }}"
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              /app/bloomcheck -serve /opt/yeti/bloomfilters
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            seccompProfile:
              type: RuntimeDefault
          env:
          {{- include "yeti.envs" . | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/yeti/bloomfilters
              name: data
          ports:
            - containerPort: 8100
              name: http
          resources:
            {{- toYaml .Values.bloomcheck.resources | nindent 12 }}
      {{- with .Values.bloomcheck.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.arangodb.persistence.size }}