{{- if and (.Values.global.ingress.enabled) (.Values.global.ingress.gcp.managedCertificates) }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Release.Name }}-osdfir-managed-ssl
  namespace: {{ .Release.Namespace | quote }}
spec:
  domains:
    {{- if and .Values.global.timesketch.enabled .Values.global.ingress.timesketchHost }}
    - {{ .Values.global.ingress.timesketchHost }}
    {{- end }}
     {{- if and .Values.global.yeti.enabled .Values.global.ingress.yetiHost }}
    - {{ .Values.global.ingress.yetiHost }}
    {{- end }}
{{- end }}