apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-openrelik-api
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: api
    {{- include "openrelik.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      {{- include "openrelik.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        {{- include "openrelik.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: false
      hostIPC: false
      automountServiceAccountToken: false
      {{- if .Values.config.enableServiceAccount }}
      serviceAccountName: openrelik
      {{- end }}
      initContainers:
      {{- include "openrelik.initContainerApi" . | nindent 8 }}
      {{- include "openrelik.initContainer" . | nindent 8 }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          command: ["/bin/sh", "-c", "uvicorn main:app --proxy-headers --forwarded-allow-ips '*' --workers 1 --host 0.0.0.0 --port 8710"]
          {{- if and (not .Release.IsUpgrade) (.Values.config.createUser) }}
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                    # Upgrade sql datastore
                    cd /app/openrelik/datastores/sql && alembic upgrade head
                    # Create OpenRelik user if it does not exist.
                    cd /app/openrelik
                    if ! python admin.py user-details openrelik > /dev/null 2>&1; then 
                      python admin.py create-user openrelik --password $OPENRELIK_USER --admin
                    fi
          {{- end }}
          env:
            - name: OPENRELIK_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-openrelik-secret 
                  key: openrelik-user
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                    name: {{ .Release.Name }}-openrelik-secret 
                    key: redis-url
            - name: SQLALCHEMY_DATABASE_URL
              valueFrom:
                secretKeyRef:
                    name: {{ .Release.Name }}-openrelik-secret 
                    key: postgres-url
            - name: PROMETHEUS_SERVER_URL
              value: http://{{ .Release.Name }}-openrelik-prometheus:9090
            {{- if .Values.config.vertex.serviceAccountSecret }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/vertex/vertex-sa.json
            - name: VERTEXAI_PROJECT_ID
              value: {{ .Values.config.vertex.projectID }}
            - name: VERTEXAI_LOCATION
              value: {{ .Values.config.vertex.location }}
            - name: VERTEXAI_DEFAULT_MODEL
              value: {{ .Values.config.vertex.model }}
            {{- end }}
            {{- if .Values.api.env }}
              {{- toYaml .Values.api.env | nindent 12 }} 
            {{- end }}
          volumeMounts:
            - mountPath: /mnt/openrelikvolume
              name: openrelikvolume
            - mountPath: /app/settings.toml
              subPath: settings.toml
              name: openrelik-configs-dir
            {{- if .Values.config.vertex.serviceAccountSecret }}
            - mountPath: /etc/vertex/vertex-sa.json
              name: vertex-sa
              subPath: vertex-sa.json
              readOnly: true
            {{- end }}
          ports:
            - containerPort: 8710
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      volumes:
        - name: openrelikvolume
          persistentVolumeClaim:
            {{- if .Values.persistence.existingPVC }}
            claimName: {{ .Values.persistence.existingPVC }}
            {{- else }}
            claimName: {{ .Release.Name }}-openrelikvolume-claim
            {{- end }}
            readOnly: false
        - name: settings-config
          configMap:
            name: {{ .Release.Name }}-openrelik-configmap
        - name: openrelik-configs-dir
          emptyDir: {}
        - name: init-oidc
          configMap:
            name: {{ .Release.Name }}-openrelik-init-oidc
            defaultMode: 0744
        {{- if .Values.config.oidc.authenticatedEmailsFile.enabled }}
        - name: authenticated-emails
          secret:
            items:
            - key: authenticated-emails-list
              path: authenticated-emails-list
            secretName: {{ include "openrelik.oidc.authenticatedemails" . }}
        {{- end }}
        {{- if .Values.config.vertex.serviceAccountSecret }}
        - name: vertex-sa
          secret:
            secretName: {{ .Values.config.vertex.serviceAccountSecret }}
        {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}