{{- range .Values.workers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        {{- if and .privileged $.Values.config.gkeAllowList }}
        cloud.google.com/matching-allowlist: {{ $.Values.config.gkeAllowList }}
        {{- end }}
    spec:
      {{- if and .privileged $.Values.config.initWorkerNbd.enabled }}
      initContainers:
      {{- include "openrelik.initContainerWorker" $ | nindent 8 }}
      {{- end }}
      hostNetwork: false
      hostIPC: false
      automountServiceAccountToken: false
      containers:
        - name: worker
          image: {{ .image | quote }}
          imagePullPolicy: "IfNotPresent"
          command: ["/bin/sh", "-c"]
          args: ["{{ .command }}"]
          securityContext:
            privileged: {{ .privileged }}
          env:
          {{- if and (eq .name "openrelik-worker-timesketch") $.Values.global.timesketch.enabled }}
            - name: TIMESKETCH_SERVER_URL
              value: {{ printf "http://%s-timesketch:5000" $.Release.Name | quote }}
            - name: TIMESKETCH_USERNAME
              value: timesketch
            - name: TIMESKETCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-timesketch-secret" $.Release.Name | quote }}
                  key: timesketch-user
          {{- else if .env }}
            {{- toYaml .env | nindent 12 }} 
          {{- end }}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                    name: {{ $.Release.Name }}-openrelik-secret 
                    key: redis-url
          volumeMounts:
            - mountPath: /mnt/openrelikvolume
              name: openrelikvolume
            {{- if and .privileged $.Values.config.initWorkerNbd.enabled }}
            - mountPath: /dev
              name: dev
              readOnly: true
            {{- end }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: openrelikvolume
          persistentVolumeClaim:
            {{- if $.Values.persistence.existingPVC }}
            claimName: {{ $.Values.persistence.existingPVC }}
            {{- else }}
            claimName: {{ $.Release.Name }}-openrelikvolume-claim
            {{- end }}
            readOnly: false
        {{- if and .privileged $.Values.config.initWorkerNbd.enabled }}
        - name: dev
          hostPath:
            path: /dev
        - name: modules
          hostPath:
            path: /lib/modules
        {{- end }}
      nodeSelector:
        {{- range $key, $value := .nodeSelector }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
{{- end }}