apiVersion: v2
name: yeti
version: 1.0.4
description: A Helm chart for Yeti Kubernetes deployments.
keywords:
- yeti
- dfir
- threatintel
- threat-hunting
- security
home: "https://yeti-platform.io/"
dependencies:
- condition: redis.enabled
  name: redis
  version: 19.3.2
  repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Open Source DFIR
    email: osdfir-maintainers@googlegroups.com
    url: https://github.com/google/osdfir-infrastructure
sources:
- https://github.com/yeti-platform/yeti
- https://github.com/google/osdfir-infrastructure
appVersion: "latest"
annotations:
  category: Security
  licenses: Apache-2.0
