{{- if or .Values.gcp.enabled .Values.config.enableServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openrelik
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openrelik.labels" . | nindent 4 }}
{{- end }}