apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-timesketch-v3
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app.kubernetes.io/component: frontend-v3
    {{- include "timesketch.selectorLabels" . | nindent 4 }}