apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-timesketch-v3
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: frontend-v3
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend-v3
      {{- include "timesketch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Restart pod if values.yaml parameters that affect the config were changed
        checksum/config: {{  include (print $.Template.BasePath "/init-configmap.yaml") . | sha256sum }}
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/component: frontend-v3
        {{- include "timesketch.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: false
      hostIPC: false
      automountServiceAccountToken: false
      initContainers:
      {{- include "timesketch.initContainer" . | nindent 8 }}
      containers:
        - name: frontend-v3
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c", "gunicorn --bind 0.0.0.0:5000 --capture-output --log-level {{ .Values.config.logLevel }} --timeout {{ .Values.config.wsgiTimeout }} --workers {{ .Values.config.wsgiWorkers }} --limit-request-line {{ .Values.config.wsgiLimitRequestLine }} --max-requests 1000 --max-requests-jitter 100 timesketch.wsgi:application"]
          env:
            - name: TIMESKETCH_UI_MODE
              value: "v3"
            {{- if .Values.config.gcp.vertexServiceAccountSecret }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/vertex/vertex-sa.json
            {{- end }}
          volumeMounts:
            - mountPath: /mnt/timesketchvolume
              name: timesketchvolume
            - mountPath: /etc/timesketch
              name: timesketch-configs
            - mountPath: /tmp
              name: tmp
            {{- if .Values.opensearch.selfSigned }}
            - mountPath: /etc/opensearch-tls
              name: opensearch-tls
            {{- end }}
            {{- if .Values.config.gcp.vertexServiceAccountSecret }}
            - mountPath: /etc/vertex/vertex-sa.json
              name: vertex-sa
              subPath: vertex-sa.json
              readOnly: true
            {{- end }}
          ports:
            - containerPort: 8080
            - containerPort: 5000
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      volumes:
        - name: timesketchvolume
          persistentVolumeClaim:
            {{- if .Values.persistence.existingPVC }}
            claimName: {{ .Values.persistence.existingPVC }}
            {{- else }}
            claimName: {{ .Release.Name }}-timesketchvolume-claim
            {{- end }}
            readOnly: false
        - name: init-timesketch
          configMap:
            name: {{ .Release.Name }}-timesketch-init-configmap
            defaultMode: 0744
        - name: timesketch-configs
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        {{- if .Values.config.existingConfigMap }}
        - name: uploaded-configs
          configMap:
            name: {{ .Values.config.existingConfigMap }}
        {{- end }}
        {{- if .Values.config.oidc.authenticatedEmailsFile.enabled }}
        - name: authenticated-emails
          secret:
            items:
            - key: authenticated-emails-list
              path: authenticated-emails-list
            secretName: {{ include "timesketch.oidc.authenticatedemails" . }}
        {{- end }}
        {{- if .Values.opensearch.selfSigned }}
        - name: opensearch-tls
          secret:
            secretName: {{ .Release.Name }}-opensearch-tls
            defaultMode: 0600
        {{- end }}
        {{- if .Values.config.gcp.vertexServiceAccountSecret }}
        - name: vertex-sa
          secret:
            secretName: {{ .Values.config.gcp.vertexServiceAccountSecret }}
        {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
