apiVersion: v1
kind: Secret
metadata:
  name: {{ template "timesketch.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
data:
  {{- if .Release.IsUpgrade }}
  {{ $secretName := printf "%s-secret" (include "timesketch.fullname" .) }}
  timesketch-secret: {{ index (lookup "v1" "Secret" .Release.Namespace $secretName).data "timesketch-secret" }}
  timesketch-user: {{ index (lookup "v1" "Secret" .Release.Namespace $secretName).data "timesketch-user" }}
  {{- else }}
  timesketch-secret: {{ randAlphaNum 32 | b64enc | quote }}
  timesketch-user: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}