apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-openrelik-nginx-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openrelik.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 8711;
        listen [::]:8711;
        client_max_body_size 0m;
        location / {
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            proxy_pass http://{{ .Release.Name }}-openrelik:8711/;
            proxy_read_timeout 600s;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    server {
        listen 8710;
        listen [::]:8710;
        client_max_body_size 0m;
        location / {
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            proxy_pass http://{{ .Release.Name }}-openrelik-api:8710/;
            proxy_read_timeout 600s;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }