apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-openrelik-nginx
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openrelik.labels" . | nindent 4 }}
  {{- if (eq .Values.global.ingress.className "gce") }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"8710":"{{ .Release.Name }}-openrelik-api-backend-config"}, "8711":"{{ .Release.Name }}-openrelik-backend-config"}'
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8710
      protocol: TCP
      targetPort: 8710
    - name: frontend
      port: 8711
      protocol: TCP
      targetPort: 8711
  selector:
    app.kubernetes.io/component: openrelik-nginx
    {{- include "openrelik.selectorLabels" . | nindent 4 }}