{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "turbinia.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "turbinia.labels" . | nindent 4 }}
  {{- if .Values.gcp.enabled }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpName }}@{{ .Values.gcp.projectID }}.iam.gserviceaccount.com
  {{- end }}
{{- end }}
